@startuml
/'
  Docs:
  https://plantuml.com/guide

  Online creator:
  https://www.planttext.com/

  Examples:
  https://real-world-plantuml.com/ 
'/
skinparam titleBorderRoundCorner 10
skinparam titleBorderThickness 2
skinparam titleBorderColor lightblue
skinparam titleBackgroundColor #D3D3D3

title App module dependecies

rectangle app #white
rectangle interfaces #LightGrey
rectangle auth #yellow
rectangle auth_ui #lightblue
rectangle ui #lightblue
rectangle notes_ui #lightblue
rectangle net #yellow

app --> auth_ui
app --> ui
app --> interfaces
app --> notes_ui
auth_ui --> ui 
auth_ui --> auth
auth_ui --> net
auth_ui --> notes_ui
auth_ui --> interfaces
auth --> interfaces
auth --> net
notes_ui --> ui
net --> interfaces

note as Description
  Modules:
  Blue color - UI layer 
  Yellow color - Domain layer
  Grey color - Platform interface module
end note

@enduml