/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_core_security_impl_HashAlgorithms */

#ifndef _Included_com_example_core_common_log_impl_LogImpl
#define _Included_com_example_core_common_log_impl_LogImpl

#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT void JNICALL Java_com_example_core_log_LogImpl__1setTag(JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif

#endif
