/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#ifndef _Included_com_example_client_app_MainActivity
#define _Included_com_example_client_app_MainActivity
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT void JNICALL Java_com_serhii_apps_notes_activities_NotesViewActivity_initNativeConfigs
  (JNIEnv *, jobject, jstring);

JNIEXPORT void JNICALL Java_com_serhii_apps_notes_activities_NotesViewActivity_notifyOnStop
  (JNIEnv *, jobject);

JNIEXPORT void JNICALL Java_com_serhii_apps_notes_activities_NotesViewActivity_notifyOnResume
        (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
