/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#ifndef _Included_com_example_client_app_net_Channel
#define _Included_com_example_client_app_net_Channel
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT void JNICALL Java_com_serhii_apps_notes_control_auth_AuthManager_requestAuthorization
  (JNIEnv *, jobject, jstring, jstring);

JNIEXPORT void JNICALL Java_com_serhii_apps_notes_control_auth_AuthManager_requestRegistration
        (JNIEnv *, jobject, jstring, jstring, jstring);

JNIEXPORT void JNICALL Java_com_serhii_apps_notes_control_auth_AuthManager_requestUnlock
        (JNIEnv *, jobject, jstring, jstring);

JNIEXPORT void JNICALL Java_com_serhii_apps_notes_control_auth_AuthManager_requestBiometricLogin
        (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
