/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_client_app_LoginActivity */

#ifndef _Included_com_example_client_app_LoginActivity
#define _Included_com_example_client_app_LoginActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_client_app_LoginActivity
 * Method:    initNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_notes_test_AuthorizationActivity_initNative
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
