/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_notes_test_NoteEditorActivity */

#ifndef _Included_com_example_notes_test_NoteEditorActivity
#define _Included_com_example_notes_test_NoteEditorActivity
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT void JNICALL Java_com_example_notes_test_NoteEditorActivity_initNativeConfigs
  (JNIEnv *, jobject);

JNIEXPORT void JNICALL Java_com_example_notes_test_NoteEditorActivity_notifyOnDestroy
        (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
