/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_client_app_MainActivity */

#ifndef _Included_com_example_client_app_MainActivity
#define _Included_com_example_client_app_MainActivity
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT void JNICALL Java_com_example_notes_test_NotesViewActivity_initNativeConfigs
  (JNIEnv *, jobject, jstring);

JNIEXPORT void JNICALL Java_com_example_notes_test_NotesViewActivity_notifyOnStop
  (JNIEnv *, jobject);

JNIEXPORT void JNICALL Java_com_example_notes_test_NotesViewActivity_notifyOnResume
        (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
