/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_client_app_net_Channel */

#ifndef _Included_com_example_client_app_net_Channel
#define _Included_com_example_client_app_net_Channel
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT void JNICALL Java_com_example_notes_test_control_managers_AuthorizeManager_requestAuthorization
  (JNIEnv *, jobject, jstring, jstring);

JNIEXPORT void JNICALL Java_com_example_notes_test_control_managers_AuthorizeManager_requestRegistration
        (JNIEnv *, jobject, jstring, jstring, jstring);

JNIEXPORT void JNICALL Java_com_example_notes_test_control_managers_AuthorizeManager_requestUnlock
        (JNIEnv *, jobject, jstring);

JNIEXPORT void JNICALL Java_com_example_notes_test_control_managers_AuthorizeManager_requestBiometricLogin
        (JNIEnv *, jobject);

JNIEXPORT void JNICALL Java_com_example_notes_test_control_managers_AuthorizeManager_requestUnlockKeystore
        (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
