/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#ifndef _Included_com_example_client_app_control_NativeBridge
#define _Included_com_example_client_app_control_NativeBridge
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jstring JNICALL Java_com_serhii_apps_notes_control_NativeBridge__1getUserName
        (JNIEnv *, jobject);

JNIEXPORT jboolean JNICALL Java_com_serhii_apps_notes_control_NativeBridge__1verifyPassword
        (JNIEnv *, jobject, jstring username, jstring password);

JNIEXPORT jboolean JNICALL Java_com_serhii_apps_notes_control_NativeBridge__1setNewPassword
        (JNIEnv *, jobject, jstring password);

JNIEXPORT void JNICALL Java_com_serhii_apps_notes_control_NativeBridge__1clearAppData
        (JNIEnv *, jobject);

JNIEXPORT jint JNICALL Java_com_serhii_apps_notes_control_NativeBridge__1getAttemptLimit
        (JNIEnv *, jobject);

JNIEXPORT jint JNICALL Java_com_serhii_apps_notes_control_NativeBridge__1getLimitLeft
        (JNIEnv *, jobject);

JNIEXPORT void JNICALL Java_com_serhii_apps_notes_control_NativeBridge__1setAttemptLimit
        (JNIEnv *, jobject, jint);

JNIEXPORT void JNICALL Java_com_serhii_apps_notes_control_NativeBridge__1setLimitLeft
        (JNIEnv *, jobject, jint);

JNIEXPORT void JNICALL Java_com_serhii_apps_notes_control_NativeBridge__1executeBlockApp
        (JNIEnv *, jobject);

JNIEXPORT jboolean JNICALL Java_com_serhii_apps_notes_control_NativeBridge__1isAppBlocked
        (JNIEnv *, jobject);

JNIEXPORT jstring JNICALL Java_com_serhii_apps_notes_control_NativeBridge__1getUnlockKey
        (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
