name: Project Build

on:
  push:
    branches: [ "master", "notes_for_desktop_app" ]
  pull_request:
    branches: [ "master", "notes_for_desktop_app" ]

jobs:
  # Job 1: Build Android target
  build-android:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        api-level: [26]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true 
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'
          cache: gradle

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v5

      - name: Build Android
        run: |
          chmod +x tools/build.sh
          ./tools/build.sh

      - name: "Cache AVD"
        uses: actions/cache@v4
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-v${{ matrix.api-level }}

      - name: Run Android tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          force-avd-creation: false
          emulator-options: "-no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none"
          disable-animations: true
          arch: x86_64
          script: chmod +x tools/run_tests.sh && ./tools/run_tests.sh

      - name: Upload Android Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Android_Artifact
          # NOTE: Verify if your output is actually in /Notes-App or in /app/build/outputs/apk/
          path: "**/build/outputs/apk/**/*.apk" 
          if-no-files-found: warn

  # Job 2: Build JVM Desktop target
  build-jvm-desktop:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true 
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'
          cache: gradle

      - name: Build Jvm Desktop
        run: |
          chmod +x tools/build_jvm_desktop.sh
          ./tools/build_jvm_desktop.sh

      - name: Upload Desktop Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: JVM_Desktop_Artifact
          path: "**/build/compose/jars/*.jar"
          if-no-files-found: warn